version: 3.4.0.{build}

branches:

  only:

  - master

skip_non_tags: true

image: Visual Studio 2017 Preview

configuration: Release

assembly_info:

  patch: true

  file: '**\AssemblyInfo.*'

  assembly_version: '{version}'

  assembly_file_version: '{version}'

  assembly_informational_version: '{version}'

before_build:

- cmd: dotnet restore src\

build:

  project: src\SqlFu\SqlFu.csproj

  verbosity: quiet

test: off

artifacts:

- path: '**\*.nupkg'

  name: nuget

deploy:

- provider: NuGet

  api_key:

    secure: zSSdZy/TonHwA3Ltpb2LbBy5zD8+YfYFBayFHPSlkUwR2bj5L9/1MSpMVCqPCCwj
