version: 3.4.0.{build}

branches:

  only:

  - master

image: Visual Studio 2017 Preview

configuration: Release

assembly_info:

  patch: true

  file: '**\AssemblyInfo.*'

  assembly_version: '{version}'

  assembly_file_version: '{version}'

  assembly_informational_version: '{version}'

before_build:

- cmd: dotnet restore src\

build:

  project: src\SqlFu\SqlFu.csproj

  verbosity: quiet

test: off

artifacts:

- path: '**\*.nupkg'

  name: nuget

deploy:

- provider: NuGet

  api_key:

    secure: UV4wi5mwnxKE84Iq66ICuliIpB58Gl9siNdPMNv6mh7HsAAscGH65AeeDUSA1K2wX0mN40KnKJcKJmly1kCgCcA2zTvXU13taZj3kbHOWd8=